### ISSUE TITLE
Failed to install/enable NFS client

### ISSUE THREAD

**Issue by rajeshjaga** [ChrisTitusTech/winutil#1786]
**Describe the bug**
There is a bunch of exception error occurring while trying to enable/install NFS Client on Windows 11 Home

**To Reproduce**
1. Go to 'Config' Tab
2. Click on 'NFS - Network File System'
3. Then click 'Install Feature'
4. See errors in the shell 

**Expected behavior**
Get/Install NFS client feature.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/23053792/470c1cdb-4de0-4150-8043-55d0fcf4d907)
After clicking "install Feature", shell throws the issue occured

```
Installing ServicesForNFS-ClientOnly
WARNING: Unable to Install ServicesForNFS-ClientOnly due to unhandled exception
WARNING:    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Installing ClientForNFS-Infrastructure
WARNING: Unable to Install ClientForNFS-Infrastructure due to unhandled exception
WARNING:    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Installing NFS-Administration
WARNING: Unable to Install NFS-Administration due to unhandled exception
WARNING:    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Running Script for WPFFeaturenfs
WARNING: Unable to Install NFS-Administration due to unhandled exception
WARNING:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
Running Script for WPFFeaturenfs
Running Script for WPFFeaturenfs
Running Script for WPFFeaturenfs
WARNING: Unable to Install NFS-Administration due to unhandled exception
WARNING:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
Running Script for WPFFeaturenfs
WARNING: Unable to Install NFS-Administration due to unhandled exception
WARNING:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
===================================
---   Features are Installed    ---
---  A Reboot may be required   ---
===================================
```

**Additional context**
For ref I'm using Windows 11 Home OsVersion : 10.0.22631, OsBuildNumber : 22631

**Comment by YusufKhalifadev** [comment]
what version of Powershell are you using?

**Comment by rajeshjaga** [comment]
> what version of Powershell are you using?

```
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rajeshjaga** [comment]
System seems to be up to date. I have tried on couple other windows 11 home machines and they are reproducing the same exception error. Also I think it could be only windows home version that might have been causing this issue, will try out on few VM's

**Comment by YusufKhalifadev** [comment]
> System seems to be up to date. I have tried on couple other windows 11 home machines and they are reproducing the same exception error. Also I think it could be only windows home version that might have been causing this issue, will try out on few VM's

Yup, its probably windows.home issue I will try looking more into that to see what makes home fails to install winget.

**Comment by ruxunderscore** [comment]
@rajeshjaga Can you launch Optional Features (Win+R > OptionalFeatures) and tell me if you see Services for NFS in there?

**Comment by rajeshjaga** [comment]
I don't see that option 
![image](https://github.com/ChrisTitusTech/winutil/assets/23053792/69226d46-3e4f-4085-9cfb-297373852162)

**Comment by ruxunderscore** [comment]
Yeah. Looks like Home doesn't seem to have the NFS client, which seems like a weird thing to not include.
