### ISSUE TITLE
ShellFeedsTaskbarViewMode cannot be set with Explorer.Exe running

### ISSUE THREAD

**Issue by Jvella94** [ChrisTitusTech/winutil#2733]
## Describe the bug
When running the "**Disable Telemetry**" Tweak, I get the below error:
```
Set HKCU:\Software\Microsoft\Windows\CurrentVersion\Feeds\ShellFeedsTaskbarViewMode to 2
WARNING: Unable to set ShellFeedsTaskbarViewMode due to unhandled exception
WARNING:    at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.PowerShell.Commands.RegistryProvider.SetRegistryValue(IRegistryWrapper key, String propertyName, Object value, RegistryValueKind kind, String path, Boolean writeResult)
   at Microsoft.PowerShell.Commands.RegistryProvider.SetProperty(String path, PSObject propertyValue)
``` 

I confirmed this by manually trying to do myself in regedit and not being allowed.

Searching led me to a [Reddit Post](https://www.reddit.com/r/sysadmin/comments/s1iomh/news_and_weather_feeds_registry_key_keeps/hw0soe4/?context=3) with the solution below:
```
# Turn off News and Interests
Write-Host "Turning off News and Interests..."
TASKKILL /IM explorer.exe /F
Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Feeds" -Name "ShellFeedsTaskbarViewMode" -Type DWord -Value 2
Start-Process explorer.exe
```

A follow up comment also recommended to disable/create two other registry entries:
```
Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Feeds" -Name "IsFeedsAvailable" -Type DWord -Value 0
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds" -Name "EnableFeeds" -Type DWord -Value 0  
```

## To Reproduce
1. Run tool -> Tweaks Tab -> Check Disable Telemetry under Essential Tweaks -> Click Run Tweaks
2. Console will show Error Message Listed as above

## Expected behavior

Registry tweaks are set correctly (a warning should come up for this option as restarting explorer.exe will remove peoples open folders etc)
## Screenshots

N/A
## Additional context

OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631

**Comment by kydex** [comment]
I've got the same error

**Comment by furquim87** [comment]
Same error here. I tried to use the solutions recommended by the OP, but it also didn't work.

**Comment by 0nelight** [comment]
I found another workaround based on a powershell script on [tenforums](https://www.tenforums.com/general-support/215088-tweaking-question-shellfeedstaskbarviewmode-access-denied-post2644410.html?s=5147335216c58f8f24a9694db982e7a3#post2644410) which links to [mydigitallife](https://forums.mydigitallife.net/threads/taskbarda-widgets-registry-change-is-now-blocked.88547/#post-1849006) which is working for me 😃.

**Comment by ghost** [comment]
fixed /close
