### ISSUE TITLE
Telemetry cannot be disabled

### ISSUE THREAD

**Issue by ArtFlag** [ChrisTitusTech/winutil#2742]
## Describe the bug

Thanks for this great tool 🙌 !

Everything's working as expected on my computer except for "Disable telemetry", 

It fails with the following error:

```
WARNING: Unable to set ShellFeedsTaskbarViewMode due to unhandled exception
WARNING:    at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.PowerShell.Commands.RegistryProvider.SetRegistryValue(IRegistryWrapper key, String propertyName, Object
       value, RegistryValueKind kind, String path, Boolean writeResult)
   at Microsoft.PowerShell.Commands.RegistryProvider.SetProperty(String path, PSObject propertyValue)
```

<details>
<summary><b>Full logs</b></summary>

```
====Chris Titus Tech=====
=====Windows Toolbox=====
===========================================
---        Winget is installed          ---
===========================================
Version: v1.8.1911
    - Winget is a release version.
    - Winget is Up to Date
Getting Installed Tweaks...
Done...
Disabling Scheduled Task Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser
Disabling Scheduled Task Microsoft\Windows\Application Experience\ProgramDataUpdater
WARNING: Scheduled Task Microsoft\Windows\Application Experience\ProgramDataUpdater was not Found
Disabling Scheduled Task Microsoft\Windows\Autochk\Proxy
Disabling Scheduled Task Microsoft\Windows\Customer Experience Improvement Program\Consolidator
Disabling Scheduled Task Microsoft\Windows\Customer Experience Improvement Program\UsbCeip
Disabling Scheduled Task Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector
Disabling Scheduled Task Microsoft\Windows\Feedback\Siuf\DmClient
Disabling Scheduled Task Microsoft\Windows\Feedback\Siuf\DmClientOnScenarioDownload
Disabling Scheduled Task Microsoft\Windows\Windows Error Reporting\QueueReporting
Disabling Scheduled Task Microsoft\Windows\Application Experience\MareBackup
Disabling Scheduled Task Microsoft\Windows\Application Experience\StartupAppTask
Disabling Scheduled Task Microsoft\Windows\Application Experience\PcaPatchDbTask
Disabling Scheduled Task Microsoft\Windows\Maps\MapsUpdateTask
Set HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection\AllowTelemetry to 0
Set HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection\AllowTelemetry to 0
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\ContentDeliveryAllowed to 0
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\OemPreInstalledAppsEnabled to 0
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\PreInstalledAppsEnabled to 0
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\PreInstalledAppsEverEnabled to 0
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SilentInstalledAppsEnabled to 0
Set HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SubscribedContent-338387Enabled to 0
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SubscribedContent-338388Enabled to 0
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SubscribedContent-338389Enabled to 0
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SubscribedContent-353698Enabled to 0
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SystemPaneSuggestionsEnabled to 0
Set HKCU:\SOFTWARE\Microsoft\Siuf\Rules\NumberOfSIUFInPeriod to 0
Set HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection\DoNotShowFeedbackNotifications to 1
Set HKCU:\SOFTWARE\Policies\Microsoft\Windows\CloudContent\DisableTailoredExperiencesWithDiagnosticData to 1
Set HKLM:\SOFTWARE\Policies\Microsoft\Windows\AdvertisingInfo\DisabledByGroupPolicy to 1
Set HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting\Disabled to 1
Set HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Config\DODownloadMode to 1
Set HKLM:\SYSTEM\CurrentControlSet\Control\Remote Assistance\fAllowToGetHelp to 0
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\OperationStatusManager\EnthusiastMode to 1
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\ShowTaskViewButton to 0
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People\PeopleBand to 0
Set HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\LaunchTo to 1
Set HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled to 1
Set HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DriverSearching\SearchOrderConfig to 1
Set HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\SystemResponsiveness to 0
Set HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\NetworkThrottlingIndex to 4294967295
Set HKCU:\Control Panel\Desktop\MenuShowDelay to 1
Set HKCU:\Control Panel\Desktop\AutoEndTasks to 1
Set HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\ClearPageFileAtShutdown to 0
Set HKLM:\SYSTEM\ControlSet001\Services\Ndu\Start to 2
Set HKCU:\Control Panel\Mouse\MouseHoverTime to 400
Set HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters\IRPStackSize to 30
Set HKCU:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds\EnableFeeds to 0
Set HKCU:\Software\Microsoft\Windows\CurrentVersion\Feeds\ShellFeedsTaskbarViewMode to 2
WARNING: Unable to set ShellFeedsTaskbarViewMode due to unhandled exception
WARNING:    at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.PowerShell.Commands.RegistryProvider.SetRegistryValue(IRegistryWrapper key, String propertyName, Object
 value, RegistryValueKind kind, String path, Boolean writeResult)
   at Microsoft.PowerShell.Commands.RegistryProvider.SetProperty(String path, PSObject propertyValue)
Set HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\HideSCAMeetNow to 1
Set HKCU:\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement\ScoobeSystemSettingEnabled to 0
Running Script for WPFTweaksTele
=================================
--     Tweaks are Finished    ---
=================================
```

</details>

Not sure how to fix this, whether it's on my end, or on WinUtil's? 

Thanks!

## Additional context

- Windows 11 home / latest version as of today.

**Comment by 4yman-0** [comment]
It failed because it can't set ShellFeedsTaskbarViewMode in Windows Registry for some unknown reason.
Is the script running as admin?

**Comment by ArtFlag** [comment]
Yes, I'm running as admin.

**Comment by ArtFlag** [comment]
Oh, funniest thing is if I run it again, it almost works. I only have one warning left (that was present in my original message, I didn't notice, line 3 in the full log):

```
Disabling Scheduled Task Microsoft\Windows\Application Experience\ProgramDataUpdater
WARNING: Scheduled Task Microsoft\Windows\Application Experience\ProgramDataUpdater was not Found
```

But somehow, Disable telemetry shows as enabled when I click `Get Installed`.

**Comment by 4yman-0** [comment]
It works now. Close this issue and see #2264 (Error while disabling Scheduled Task Microsoft\Windows\Application Experience\ProgramDataUpdater)

**Comment by MyDrift-user** [comment]
closing this out now since it is a duplicate either way, thanks for reporting and looking into it tho :)

/close
