### ISSUE TITLE
Unable to set ShellFeedsTaskbarViewMode due to unhandled exception

### ISSUE THREAD

**Issue by magor34** [ChrisTitusTech/winutil#2977]
## Describe the bug
Set HKCU:\Software\Microsoft\Windows\CurrentVersion\Feeds\ShellFeedsTaskbarViewMode to 2
WARNING: Unable to set ShellFeedsTaskbarViewMode due to unhandled exception
WARNING:    at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.PowerShell.Commands.RegistryProvider.SetRegistryValue(IRegistryWrapper key, String propertyName, Object value, RegistryValueKind kind, String path, Boolean writeResult)
   at Microsoft.PowerShell.Commands.RegistryProvider.SetProperty(String path, PSObject propertyValue).

No amount of restarts to OS or app does anything.
Winver: 24H2 (26100.2161).
Powershell 7 is up to date.
The error started occurring after installing this version, to my knowledge I never got this error before. System corruption scan shows no errors.
The only system tweak I've done outside of winutil is disabling Windows Driver Downloading in the gpedit.msc. So I can download new 24H2 fixes without WinUpdate downloading new NVIDIA drivers that arent stable.

## To Reproduce
1. Running "Standard" Tweaks preset.

## Expected behavior
Other than not getting said error... I don't know. I'm a newbie.

**Comment by zmileski** [comment]
#2733
