### ISSUE TITLE
 Unable to set TaskbarDa due to unhandled exception

### ISSUE THREAD

**Issue by genifycom** [ChrisTitusTech/winutil#2988]
## To Reproduce
Tried to Disable GameDVR, Hibernation, Homegroup, Microsoft Copilot.
Set Display for performance, Classic Right-Menu.
Remove OneDrive

## Screenshots
WARNING: Unable to set TaskbarDa due to unhandled exception
WARNING:    at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.PowerShell.Commands.RegistryProvider.SetRegistryValue(IRegistryWrapper key, String propertyName, Object
 value, RegistryValueKind kind, String path, Boolean writeResult)
   at Microsoft.PowerShell.Commands.RegistryProvider.SetProperty(String path, PSObject propertyValue)

**Comment by zmileski** [comment]
Duplicate of #2886

**Comment by ghost** [comment]
fixed /close
