### ISSUE TITLE
Winget cannot be accessed in MicroWin installation

### ISSUE THREAD

**Issue by runitmisra** [ChrisTitusTech/winutil#3077]
## Describe the bug
Winget cannot be accessed in MicroWin installation. Getting the following error:
```
====Chris Titus Tech=====
=====Windows Toolbox=====
@{winget=Discord.Discord; choco=discord}
Queueing Discord.Discord for Winget install
WARNING: Winget was not found due to un-availablity reasons
Deployment operation progress: https://cdn.winget.microsoft.com/cache/source.msix
Processing
[oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo]
Downloading Winget Prerequsites

Downloading Microsoft.VCLibs Dependency...
Downloading Microsoft.UI.Xaml Dependency...

Downloading Winget and License File
Latest Version: v1.9.25200

Downloading...
Installing Winget w/ Prerequsites
Manually adding Winget Sources, from Winget CDN.
Winget Installed
Enabling NuGet and Module...
===========================================
--    Configuring winget packages       ---
===========================================
===========================================
Error: This command cannot be run due to the error: The file cannot be accessed by the system.
===========================================

An error has occurred that was not properly handled. Additional information is shown below. The Windows PowerShell process will exit.

Unhandled Exception: System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeAsDelegateHelper(Object dollarUnder, Object dollarThis, Object[] args)
   at lambda_method(Closure , IntPtr , Int32 , IntPtr , IntPtr , Boolean& )
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

[process exited with code 3221226525 (0xc000041d)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

## To Reproduce
- Create MicroWin ISO from winutil (Windows 11 Pro)
- Use winutil to install anything

## Expected behavior
Package should be installed

## Screenshots
Will provide if required

## Additional context
N/A

**Comment by runitmisra** [comment]
It worked after I updated the Powershell version. Thanks!
